#pragma once
#include <vector>
#include <string>

//Source: http://fantasynamegenerators.com/

static std::vector<std::string> dungeonNames = {
	"Vault of the Mourning Emperor",
	"Tunnels of the Burning Scorpion",
	"Maze of the Scarlet Knight",
	"Tombs of the Vanished Warlord",
	"The Dreaded Caverns",
	"The Tranquil Point",
	"The Cunning Burrows",
	"The Enchanted Maze",
	"The Burned Vault",
	"The Fire Mountain Lair",
	"Grotto of the Infernal Paladin",
	"Labyrinth of the Dishonored Warrior",
	"Maze of the Rejected Witch",
	"Labyrinth of the Furious Horsemen",
	"The Invisible Chambers",
	"The Twisting Vault",
	"The Dragontooth Quarters",
	"The Gold Mine Tunnels",
	"The Chaotic Caverns",
	"The Hallucination Delves",
	"Quarters of the Rejected Lion",
	"Catacombs of the Vanishing Bear",
	"Point of the Perished Jungle",
	"Point of the Furious Witch",
	"The Dragon Burrows",
	"The Black Caverns",
	"The Crescent Moon Chambers",
	"The Deepest Grotto",
	"The Haunted Grotto",
	"The Rugged Pits",
	"Tombs of the Gentle Paladin",
	"Point of the Obsidian Queen",
	"Point of the Cruel Goblin",
	"Maze of the Crying Ogre",
	"The Courage Dungeon",
	"The Adamantite Delves",
	"The Silent Cells",
	"The Burned Crypt",
	"The Black Mountain Pits",
	"The Emerald Grotto",
	"Quarters of the Vanquished Army",
	"Haunt of the Vanquished Goblin",
	"Caverns of the Unknown Mountain",
	"Cells of the Nameless Raven",
	"The Diamond Tombs",
	"The Brutal Tombs",
	"The Grim Labyrinth",
	"The Motionless Maze",
	"The Sanguine Crypt",
	"The Dreaded Crypt",
	"Catacombs of the Mourning Mage",
	"Point of the Golden Hound",
	"Maze of the Shadow Occult",
	"Lair of the Cold Warrior",
	"The Lurking Shadow Vault",
	"The Raging Vault",
	"The Dry Point",
	"The Moaning Quarters",
	"The Enchanted Crypt",
	"The Forgotten Burrows",
	"Burrows of the Golden Bat",
	"Haunt of the Golden Knight",
	"Haunt of the Silver Oracle",
	"Chambers of the Granite King",
	"The Bare Delves",
	"The Brilliant Delves",
	"The Abysmal Chambers",
	"The Eastern Pits",
	"The Dreary Chambers",
	"The Desolated Catacombs",
	"Caverns of the Golden Basilisk",
	"Delves of the Storm Hunter",
	"Maze of the Perished Hound",
	"Crypt of the Golden Bear",
	"The Illusion Crypt",
	"The Ethereal Tombs",
	"The Black Lair",
	"The Shrieking Pits",
	"The Haunted Delves",
	"The Shimmering Labyrinth",
	"Pits of the Ebon Warlord",
	"Caverns of the Destroyed Hound",
	"Vault of the Burning Swamp",
	"Tunnels of the Vanquished Guardian",
	"The Illusion Catacombs",
	"The Bellowing Cells",
	"The Adamantine Labyrinth",
	"The Silver Crypt",
	"The Adamantine Quarters",
	"The Red Caverns",
	"Quarters of the Silver Witch",
	"Tunnels of the Frozen Witch",
	"Labyrinth of the Unknown Arachnid",
	"Grotto of the Unknown Serpent",
	"The Ender Cells",
	"The Infinite Tunnels",
	"The Dreaded Grotto",
	"The Brutal Cells",
	"The Deepwood Point",
	"The Sunken Delves",
	"Catacombs of the Fallen Serpent",
	"Crypt of the Mythic Arachnid",
	"Caverns of the Frozen Witch",
	"Grotto of the Golden Cult",
	"The Jagged Tunnels",
	"The Laughing Haunt",
	"The Jade Lair",
	"The Erased Vault",
	"The Black Quarters",
	"The Collapsing Caverns",
	"Chambers of the Betrayed Warlord",
	"Haunt of the Lost Leopard",
	"Delves of the Golden Queen",
	"Tunnels of the Poisoned Raven",
	"The Tormented Tunnels",
	"The Buried Delves",
	"The Dire Grotto",
	"The Black Forest Pits",
	"The Arching Dungeon",
	"The Violent Delves",
	"Chambers of the Renegade Warlord",
	"Delves of the Spirit Basilisk",
	"Labyrinth of the Mythic Lion",
	"Quarters of the Raging Warrior",
	"The Abomination Quarters",
	"The Death Talon Quarters",
	"The Winter Pits",
	"The Laughing Point",
	"The Dry Tombs",
	"The Oblivion Catacombs",
	"Catacombs of the Granite Bear",
	"Dungeon of the Mythic Horsemen",
	"Grotto of the Forgotten Swamp",
	"Lair of the Shrouded Morass",
	"The Smoky Quarters",
	"The Laughing Skulls Quarters",
	"The Bleak Haunt",
	"The Shimmering Tombs",
	"The Dead Burrows",
	"The Coral Chambers",
	"Caverns of the Vanishing Paladin",
	"Dungeon of the Lost Leopard",
	"Catacombs of the Shrouded Hunter",
	"Quarters of the Storm Forest",
	"The Red Pits",
	"The Mourning Burrows",
	"The Brutal Labyrinth",
	"The Lucent Caverns",
	"The Wind Delves",
	"The Goblin Vault",
	"Haunt of the Cold Wolf",
	"Burrows of the Shunned Wizard",
	"Haunt of the Chaotic Priest",
	"Burrows of the Ruthless Lion",
	"The Fallen Legion Maze",
	"The Raging Burrows",
	"The Scarlet Maze",
	"The Desolated Maze",
	"The Hollow Haunt",
	"The Black Delves",
	"Dungeon of the Cruel Giant",
	"Maze of the Poisoned Desert",
	"Grotto of the Perished Forest",
	"Burrows of the Burning Dragon",
	"The Buried Crypt",
	"The Dread Labyrinth",
	"The Vicious Crypt",
	"The Wicked Pits",
	"The Volcanic Tombs",
	"The Scarlet Catacombs",
	"Grotto of the Shadow Warrior",
	"Point of the Conquered Witch",
	"Caverns of the Crystal Marsh",
	"Chambers of the Spirit's Monk",
	"The Mocking Dungeon",
	"The Bare Chambers",
	"The Gloomy Catacombs",
	"The Fractured Grotto",
	"The Flowing Labyrinth",
	"The Adamantite Quarters",
	"Tunnels of the Nameless Monk",
	"Cells of the Mythic Witch",
	"Pits of the Forbidden Forest",
	"Vault of the Ruthless Witch",
	"The Fearsome Maze",
	"The Shimmering Point",
	"The Death Talon Tunnels",
	"The Infinite Labyrinth",
	"The Scorching Point",
	"The Cold Grotto",
	"Grotto of the Unknown Leopard",
	"Tunnels of the Unknown Jungle",
	"Pits of the Cursed Leopard",
	"Vault of the Lost Raven",
	"The Ethereal Chambers",
	"The Perfumed Cells",
	"The Whispering Shadows Haunt",
	"The Smoldering Delves",
	"The Delusion Grotto",
	"The Desolate Crypt"
};



static std::vector<std::string> characterNames = {
	"Keegan",
	"Milton",
	"Alex",
	"Urbanus",
	"Ali",
	"Paul",
	"Auhert",
	"Irving",
	"Berthold",
	"Bertolt",
	"Leva",
	"Woodie",
	"Therron",
	"Adrianus",
	"Valentino",
	"Sanborn",
	"Rigby",
	"Armani",
	"Alonso",
	"Lance",
	"Edelhart",
	"Jan",
	"Quinten",
	"Mailhairer",
	"Eppo",
	"Parry",
	"Kadin",
	"Gallus",
	"Leone",
	"Thorsten",
	"Goswin",
	"Vilmos",
	"Windham",
	"Reginald",
	"Raffaello",
	"Jesper",
	"Verel",
	"Aldwin",
	"Sven",
	"Marley",
	"Cristopher",
	"Marcel",
	"Ruben",
	"Mallory",
	"Jarred",
	"King",
	"Redford",
	"Heino",
	"Zenobio",
	"Sherm",
	"Todd",
	"Wiley",
	"Emil",
	"Xaverius",
	"Ourson",
	"Ruggero",
	"Henry",
	"Aloys",
	"Raoul",
	"Blaisdell",
	"Shawn",
	"Ransley",
	"Huprecht",
	"Jorg",
	"Destrey",
	"Carlos",
	"Vachel",
	"Wiclif",
	"Nico",
	"Pepino",
	"Fabius",
	"Draven",
	"Geffrey",
	"Geron",
	"Duval",
	"Claudio",
	"Bartlett",
	"Heini",
	"Ailen",
	"Lyle",
	"Winfrid",
	"Moor",
	"Verne",
	"Leonard",
	"Victorinus",
	"Jaromil",
	"Jesus",
	"Valiant",
	"Fremont",
	"Willie",
	"Filippo",
	"Dwight",
	"Ivan",
	"Newmie",
	"Anderl",
	"Marino",
	"Kellen",
	"Fabiano",
	"Dustyn",
	"Snowdun",
	"Audric",
	"Konrad",
	"Miso",
	"Theodorick",
	"Barnett",
	"Egbert",
	"Volkan",
	"Skrolan",
	"Edmundo",
	"Gerrit",
	"Hinz",
	"Baxter",
	"Braedon",
	"Curtice",
	"Lindon",
	"Brody",
	"Sigmond",
	"Seid",
	"Felizian",
	"Derck",
	"Mark",
	"Mateo",
	"Melton",
	"Paavo",
	"Hubertus",
	"Asher",
	"Gabriella",
	"Elyssa",
	"Delmare",
	"Dick",
	"Damia",
	"Fritzie",
	"Devin",
	"Madeleina",
	"Pyper",
	"Dragana",
	"Chere",
	"Adorlee",
	"Missye",
	"Aldercy",
	"Shandy",
	"Zeider",
	"Mariela",
	"Galla",
	"Ulrika",
	"Toni",
	"Bailey",
	"Camryn",
	"Laura",
	"Sandrina",
	"Sinje",
	"Tiana",
	"Ashlyn",
	"Adrianna",
	"Garnet",
	"Oriel",
	"Anneke",
	"Auberta",
	"Genevre",
	"Laverna",
	"Jaycee",
	"Eileen",
	"Alessandra",
	"Joceline",
	"Alejandra",
	"Calantha",
	"Morgan",
	"Meghan",
	"Cameron",
	"Rosi",
	"Rosita",
	"Dominica",
	"Skyla",
	"Chlorinde",
	"Norberta",
	"Alina",
	"Batilde",
	"Christin",
	"Berty",
	"Kylee",
	"Charlaine",
	"Raphaele",
	"Silja",
	"Floria",
	"Alita",
	"Bernadette",
	"Elyse",
	"Zina",
	"Deja",
	"Jutta",
	"Jacquenetta",
	"Taliyah",
	"Rive",
	"Lenchen",
	"Gitte",
	"Elinore",
	"Donna",
	"Wilfiede",
	"Mirjam",
	"Cheyanne",
	"Uta",
	"Adelise",
	"Aubrie",
	"Esther",
	"Saxona",
	"Kordula",
	"Martine",
	"Simonette",
	"Destini",
	"Evonne",
	"Inken",
	"Kaila",
	"Gypsy",
	"Charlize",
	"Susana",
	"Margit",
	"Joan",
	"Chanel",
	"Philippe",
	"Livi",
	"Wilfrieda",
	"Emeline",
	"Ernesta",
	"Daphne",
	"Carissa",
	"Federiga",
	"Eleonora",
	"Felina",
	"Rudelle",
	"Questa",
	"Floressa",
	"Miriam",
	"Zuria",
	"Nicky",
	"Milena",
	"Malia",
	"Rosemary",
	"Marissa",
	"Edith",
	"Ira",
	"Gertrude",
	"Precious",
	"Idda",
	"Aurica",
	"Darcia",
	"Irmine",
	"Chauntel",
	"Henriette",
	"Chantay",
	"Harley",
	"Grit",
	"Annemarie",
	"Justine",
	"Kenya",
	"Corliss",
	"Bria",
	"Margret",
	"Dela",
	"Camillei",
	"Varinka",
	"Tracy",
	"Conni",
	"Edmee",
	"Jella",
	"Olympie"
};

static std::vector<std::string> longswordNames = {
	"Venom",
	"Reaper's Toll",
	"Severance",
	"Lustful Rapier",
	"Brutal Broadsword",
	"Unholy Skeletal Broadsword",
	"Engraved Steel Guardian",
	"The Stake, Claymore of Eternal Struggles",
	"Deathbringer, Terror of Grace",
	"Gladius, Savagery of Cruelty",
	"The Untamed",
	"Oblivion",
	"Broken Promise",
	"Stormguard Crusader",
	"Firestorm Longsword",
	"Improved Glass Crusader",
	"Proud Glass Warblade",
	"Ghost Reaver, Blessed Blade of the Queen",
	"Amnesia, Mageblade of the Shadows",
	"Striker, Dark Blade of the Ancients",
	"Cometfell",
	"Blazeguard",
	"Nightfall",
	"Sapphire Infused Claymore",
	"Yearning Defender",
	"Skullforge Gold Spellblade",
	"Honed Adamantite Spellblade",
	"Arondite, Might of Insanity",
	"The Ambassador, Last Stand of Infinite Trials",
	"Betrayal, Slicer of the Dead",
	"ForgetMeNot",
	"Last Words",
	"Destiny's Song",
	"Peacekeeper Greatsword",
	"Fireguard Skewer",
	"Feral Iron Defender",
	"Thunderguard Obsidian Slicer",
	"Trinity, Slayer of the Night Sky",
	"Doomblade, Pact of Summoning",
	"Endbringer, Protector of the Forest",
	"Red Obsidian",
	"Decimation",
	"Valkyrie",
	"Tyrannical Warblade",
	"Treachery's Etcher",
	"Soul Gold Quickblade",
	"Crying Gold Rapier",
	"Silverlight, Doomblade of Shadows",
	"Sting, Vengeance of the Talon",
	"Suspension, Whisper of the Lion",
	"Extinction",
	"Echo",
	"The End",
	"Retribution Quickblade",
	"Undead Claymore",
	"Retribution Adamantite Defender",
	"Desire's Copper Warblade",
	"Spada, Hope of Magic",
	"Blazefury, Secret of Holy Might",
	"Piece Maker, Carver of the Forest",
	"Lightbane",
	"Spiteblade",
	"Worldslayer",
	"Replica Guardian",
	"Frenzied Shortsword",
	"Furious Adamantite Deflector",
	"Sharpened Mithril Greatsword",
	"Striker, Oath of Shadow Strikes",
	"Gutrender, Legacy of Burdens",
	"Savagery, Saber of Executions",
	"Eclipse",
	"Stormcaller",
	"Lifedrinker",
	"Anguish Defender",
	"Primitive Sculptor",
	"Frenzied Adamantite Greatsword",
	"Blood-Forged Diamond Broadsword",
	"Willbreaker, Dawn of Blight",
	"Loyalty, Bond of the Corrupted",
	"Extinction, Longsword of the Daywalker",
	"Mercy",
	"Broken Promise",
	"Heartstriker",
	"Amber Infused Blade",
	"Zealous Shortsword",
	"Soul Iron Claymore",
	"Soul Gold Quickblade",
	"Wolf, Defender of the Empty Void",
	"Nightbane, Destroyer of Dark Magic",
	"Lightning, Runed Blade of the Occult",
	"Prick",
	"Spineripper",
	"Betrayal",
	"Tyrannical Razor",
	"Fire Infused Skewer",
	"Vindictive Skeletal Slicer",
	"Moonlit Obsidian Katana",
	"Nethersbane, Breaker of Shadows",
	"Peacekeeper, Ferocity of the North",
	"Narcoleptic, Dark Blade of Diligence"
};


static std::vector<std::string> longbowNames = {
	"Hamstring",
	"Heartpiercer",
	"Silentsong",
	"Skeletal Warp-Bow",
	"Oak Shooter",
	"Oathkeeper's Hardwood Flatbow",
	"Soul Titanium Crossfire",
	"Rain Maker, Hope of Ancient Power",
	"Perfidy, Destroyer of Holy Might",
	"Wasp, Bow of Trials",
	"Snipe",
	"Perfidy",
	"Final Breath",
	"Titanium Shortbow",
	"Hardwood Repeater",
	"Mourning Warpwood Composite Bow",
	"Brutal Titanium Warp-Bow",
	"Tiebreaker, Champion of Traitors",
	"Quintain, Oath of Due Diligence",
	"Huntress, Foe of the Wind",
	"Squirm",
	"Fury",
	"Pierce",
	"Bronzed Bow",
	"Ironbark Flatbow",
	"Jade Infused Bronzed Hunting Bow",
	"Atuned Willow Warp-Bow",
	"Pique, Bond of Blessed Fortune",
	"Razorsong, Warp-Bow of Anguish",
	"Barrage, Gift of the Setting Sun",
	"Venomstrike",
	"Hamstring",
	"Vehement Chord",
	"Yew Bolter",
	"Ebon Shortbow",
	"Windsong Driftwood Compound Bow",
	"Bloodlord's Titanium Bow",
	"Porcupine, Defiler of the Fallen",
	"Truestrike, Crossbow of Shifting Sands",
	"Penetrator, Flatbow of the North",
	"Phantom Strike",
	"Hurricane",
	"Molten Fury",
	"Bone Piercer",
	"Yew Bow",
	"Singing Hardwood Piercer",
	"Ritual Bone Straight Bow",
	"Hedgehog, Curve of Mourning",
	"Backsnipe, Breaker of the Queen",
	"Pluck, Vengeance of the Lone Victor",
	"Tranquility",
	"Doomcaster",
	"Swiftwind",
	"Steel Composite Bow",
	"Steel Self Bow",
	"Infused Steel Striker",
	"Vindication Steel Crossbow",
	"Vulture, Whisper of Wizardry",
	"Devil's Whisper, Skewer of the Gladiator",
	"Wasp, Champion of Hate",
	"Ballista",
	"Tweak",
	"Shooting Star",
	"Driftwood Bow",
	"Hardwood Arbalest",
	"Frost Driftwood Compound Crossbow",
	"Wretched Oak Composite Bow",
	"Whelm, Flatbow of the East",
	"Siren's Cry, Crescent of the Harvest",
	"Heartstring, Heavy Crossbow of Blood",
	"Perfidy",
	"Dead Air",
	"Pierce",
	"Ashwood Bolter",
	"Iron Compound Crossbow",
	"Pride's Yew Shortbow",
	"Arched Ashwood Compound Bow",
	"Firestarter, Destroyer of Hell's Games",
	"Jugular, Ellipse of Deception",
	"Graviton, Protector of the Nightstalker",
	"Archangel",
	"Final Voyage",
	"Heartstring",
	"Ashwood Hunting Bow",
	"Redwood Shortbow",
	"Antique Skeletal Crossbow",
	"Solitude's Hardwood Speargun",
	"Bolt, Cunning of Giants",
	"Snatch, Self Bow of Thunder",
	"Death's Whisper, Chord of the Shadows",
	"Windbreaker",
	"Hatred's Sting",
	"Ballista",
	"Iron Shortbow",
	"Steel Striker",
	"Possessed Hardwood Repeater",
	"Void Bronzed Arbalest",
	"Comet, Terror of Cunning",
	"Ballista, Protector of Eternal Glory",
	"Scorpion, Repeater of Broken Families",
};


static std::vector<std::string> shieldNames = {

	"Curator",
	"The Observer",
	"Betrayal",
	"Hailstorm Shield Wall",
	"Tormented Carapace",
	"Loyal Hardwood Warden",
	"Gladiator Skeletal Bastion",
	"Betrayal, Pledge of the Forgotten",
	"Bombardment, Tribute of Blight",
	"Blind Hatred, Kite Shield of Heroes",
	"Cerberus",
	"The Ambassador",
	"Wall of Pride",
	"Fearful Kite Shield",
	"Undead Visage",
	"Wretched Bone Visage",
	"Holy Warpwood Buffer",
	"Faithkeeper, Last Stand of the Void",
	"Pride's Honor, Call of Eternal Bloodlust",
	"Thunder, Guardian of Power",
	"Alpha",
	"The Titan",
	"Sanctify",
	"Frenzied Guard",
	"Shadow Tower Shield",
	"Deserted Warpwood Carapace",
	"Malignant Bone Greatshield",
	"Malice, Bond of Agony",
	"Convergence, Terror of Bloodlust",
	"Tyranny, Defiler of Dismay",
	"Lightbringer",
	"Knight's Fall",
	"Ogre",
	"Terror Ward",
	"Brutality Keeper",
	"Guardian's Oak Buckler",
	"Vicious Bronze Buffer",
	"Blind Hate, Tribute of the Immortal",
	"Retirement, Keeper of the Lion",
	"Malice, Conservator of Grace",
	"Cataclysm",
	"Typhoon",
	"Mercy",
	"Storm Tower Shield",
	"Soldier's Buffer",
	"Knightly Golden Carapace",
	"Zealous Ebon Bulwark",
	"Cataclysm, Gift of Broken Families",
	"Supremacy, Bond of Torment",
	"Desolation, Keeper of Hate",
	"Barrage",
	"Wisdom's Grasp",
	"Shepherd",
	"Champion's Barricade",
	"Cold-Forged Buffer",
	"Cataclysmic Bone Ward",
	"Woeful Ebon Keeper",
	"Oblivion, Bastion of the Gladiator",
	"Wit's End, Vengeance of the East",
	"Shroud, Tower Shield of Pride's Fall",
	"Voice of Pride",
	"Painkiller",
	"Prelude",
	"Protector's Buffer",
	"Savage Shield Wall",
	"Possessed Mithril Greatshield",
	"War-Forged Obsidian Shield",
	"Sunward, Barricade of Ancient Power",
	"Overture, Ferocity of Horrid Dreams",
	"The End, Reach of Unholy Might",
	"Steelskin",
	"King's Legacy",
	"Stormcaller",
	"Extinction Armament",
	"Cataclysmic Visage",
	"Demonic Willow Barrier",
	"Wind's Mithril Guardian",
	"Anguish, Champion of the Setting Sun",
	"Eruption, Might of the Enigma",
	"Chaos, Tower Shield of Hatred",
	"Honor's End",
	"Death's Deflection",
	"Rand",
	"Warrior Heater",
	"Hailstorm Keeper",
	"Savage Warpwood Keeper",
	"Roaring Titanium Aegis",
	"Chaos, Breaker of Conquered Worlds",
	"Vigilant, Ward of the Nightstalker",
	"Eclipse, Reach of Inception",
	"Malice",
	"Stormcaller",
	"Mercy",
	"Ebon Heater",
	"Baneful Shield Wall",
	"Recruit's Silver Armament",
	"Dragonbreath Bone Kite Shield",
	"The Iron Maiden, Tower Shield of Heroes",
	"Triumph, Ferocity of Blessings",
	"Barrage, Wit of the Void"
};


static std::vector<std::string> helmetNames = {
	"Jaws of Hellish Justice",
	"Jaws of Twisted Vengeance",
	"Mithril Faceguard of Relentless Misery",
	"Adamantite Headcover of Damned Protection",
	"Lightning Iron Helmet",
	"Twisted Scaled Crown",
	"Victor Crown of Ancient Power",
	"Undead Faceguard of Chaos",
	"Helmet of Sunlight",
	"Death of the Damned",
	"Gaze of Frozen Illusions",
	"Visage of Eternal Vengeance",
	"Bronze Helmet of Burning Sorrow",
	"Bronze Crown of Infernal Fire",
	"Exile Demon Casque",
	"Peacekeeper Iron Helm",
	"Challenger Headguard of the Nightstalker",
	"Crying Crown of Unholy Blight",
	"Dawn of the Covenant",
	"Headcover of Stealth",
	"Helmet of Blind Honor",
	"Helmet of Blessed Bloodlust",
	"Golden Gaze of Hallowed Vengeance",
	"Silver Visage of Infernal Powers",
	"Cursed Titanium Helmet",
	"War-Forged Iron Headcover",
	"Demonic Gaze of the Lone Victor",
	"Sorrow's Helmet of Frost",
	"Gift of the Eagle",
	"Destroyer of Patience",
	"Casque of Timeless Magic",
	"Casque of Ancient Nights",
	"Silver Greathelm of Shattered Glory",
	"Ivory Headguard of Lost Fortune",
	"Fierce Bone Helmet",
	"Champion Silver Casque",
	"Terror Headcover of Assassination",
	"Thundersoul Faceguard of Vigor",
	"Tribute of Ended Dreams",
	"Shepherd of Bloodshed",
	"Headcover of Shattered Misery",
	"Helm of Damned Protection",
	"Adamantite Casque of Doomed Kings",
	"Bone Crown of Twisted Nights",
	"Cursed Silver Faceguard",
	"Vindictive Bronzed Greathelm",
	"Peacekeeper's Visage of the Shadows",
	"Shadow Jaws of Anguish",
	"Bond of Binding",
	"Vengeance of the Wind",
	"Visage of Ending Fires",
	"Helmet of Dark Nightmares",
	"Golden Visage of Eternal Vengeance",
	"Obsidian Helm of Timeless Freedom",
	"Demonic Plate Casque",
	"Vindicator Bronze Gaze",
	"Windsong Gaze of Clarity",
	"Solitude's Visage of Slaying",
	"Jaws of the Beast",
	"Crown of Burning Damnation",
	"Crown of Cursed Bloodlust",
	"Scaled Headguard of Burning Damnation",
	"Bronzed Headcover of Demonic Sorrow",
	"Bloodied Titanium Faceguard",
	"Hero Golden Jaws",
	"Tormented Gaze of Infinity",
	"Dragon Headcover of the South",
	"Pledge of Zeal",
	"Casque of Agony",
	"Crown of Hallowed Wars",
	"Faceguard of Ancient Torment",
	"Golden Helmet of Hallowed Trials",
	"Adamantite Casque of Dark Dreams",
	"Blood Infused Ebon Crown",
	"Thunderguard Bone Helmet",
	"Guard's Greathelm of the South",
	"Bandit's Headguard of Ancient Powers",
	"Favor of Devotion",
	"Memory of the Mountain",
	"Faceguard of Fleeting Might",
	"Crown of Haunted Damnation",
	"Golden Headguard of Timeless Wars",
	"Bronzed Helm of Shattered Nightmares",
	"Arcane Demon Gaze",
	"Yearning Mithril Headcover",
	"Challenger Jaws of Infinity",
	"Retribution Helmet of the Sun",
	"Token of Phantoms",
	"Vindicator of Thorns",
	"Headcover of Blessed Ancestors",
	"Crown of Ending Lands",
	"Golden Gaze of Condemned Damnation",
	"Titanium Helm of Condemned Might",
	"Barbaric Bronze Greathelm",
	"Renovated Demon Headguard",
	"Vicious Helm of the Warrior",
	"Challenger's Helm of Torment",
	"Destroyer of Chaos",
	"Memory of Ghosts",
	"Shadow Scaled Helm"
};


static std::vector<std::string> ringNames = {
	"Prismatic Band",
	"Demonic Bone Ring",
	"Opal Ring",
	"Vermilion Band",
	"Granite Ring",
	"Band of the Penitent",
	"Frigid Ring",
	"Jungle Ring",
	"Peridot Circle",
	"Corrupted Band",
	"Dragonscale Band",
	"Multicolored Band",
	"Plague Band",
	"Hardened Stone Band",
	"Quicksilver Ring",
	"Emerald Lion Ring",
	"Jasper Link",
	"Obsidian Band",
	"Ring of the Dawn",
	"Bloodwash Ring",
	"Glowing Crystal Ring",
	"Ring of Bitter Shadows",
	"Ring of Living Stone",
	"Swamp Ring",
	"Glowing Thorium Band",
	"Onslaught Ring",
	"Ring of the Heavens",
	"Chemist's Ring",
	"Dalson Family Wedding Ring",
	"Mark of Hakkar",
	"Selenium Loop",
	"Serpentine Loop",
	"Marble Circle",
	"Ring of the Aristocrat",
	"Arctic Ring",
	"Choking Band",
	"Diamond Focus Ring",
	"Ring of Pesticide",
	"Sha'ni's Ring",
	"Frostleaf Band",
	"Glassy Band",
	"Sardonyx Knuckle",
	"Simple Opal Ring",
	"Stardust Band",
	"White Bone Band",
	"Stratagem Band",
	"Thorg'izog's Band",
	"Vanadium Loop",
	"White Bone Circle",
	"Zin - Malor Ring",
	"Band of the Great Tortoise",
	"Burning Obsidian Band",
	"Ember Worg Eye",
	"Emberstone Signet",
	"Onyx Ring",
	"Seedtime Hoop",
	"Desert Ring",
	"Rendan's Signet",
	"The Aquamarine Ward",
	"Topaz Ring",
	"Band of the Unicorn",
	"Ring of Subtlety",
	"Tree Ring Band",
	"Truesilver Healing Ring",
	"Dangerous Machinery Piece",
	"Tellurium Band",
	"Aquamarine Ring",
	"Coldwater Ring",
	"Lodestone Hoop",
	"Rainbow Band",
	"Red Ring of Destruction",
	"Seafire Band",
	"Goat Horn Band",
	"Marsh Ring",
	"Petrified Band",
	"Redfeather Band",
	"Falcon's Hook",
	"Hematite Link",
	"Iridium Circle",
	"Recruit's Band",
	"Recruit's Ring",
	"Recruit's Signet",
	"Ring of the Subduer",
	"Ring of the Subduer",
	"Discarded Wedding Band",
	"Jet Loop",
	"Korfax's Signet",
	"Brivelthwerp's Signet",
	"Forest Hoop",
	"Payback Band",
	"Ring of New Life",
	"Carnelian Loop",
	"Deathguard Band",
	"Defender's Band",
	"Inscribed Gold Ring",
	"Pack Leader's Band",
	"Prismstone Ring",
	"Raptor Eye Ring",
	"Ring of Aces",
	"Hadoken Band"
};


static std::vector<std::string> beltNames = {
	"Waistband of Endless Comrades",
	"Girdle of Eternal Nightmares",
	"Demon Waistband of Broken Protection",
	"Bronzed Girdle of Fleeting Justice",
	"Frost Adamantite Gunbelt",
	"Frozen Silver Links",
	"Hero Demon Gunbelt",
	"Trainee's Waistguard of Paradise",
	"Gladiator Links of Serenity",
	"Woeful Gunbelt of Terror",
	"Band of Lost Magic",
	"Gunbelt of Timeless Memories",
	"Mithril Gunbelt of Frozen Worlds",
	"Mithril Band of Doomed Damnation",
	"Demon Chain",
	"Spite Skeletal Girdle",
	"Twilight's Demon Links",
	"Liar's Links of Broken Bones",
	"Barbaric Gunbelt of Executions",
	"Soul-Forged Cord of the Moonwalker",
	"Waistguard of Eternal Sorrow",
	"Belt of Infernal Trials",
	"Mithril Girdle of Cursed Damnation",
	"Golden Waistband of Condemned Misery",
	"Battleworn Iron Waistband",
	"Twisted Adamantite Waistband",
	"Yearning Bronze Cord",
	"Hopeless Chain of Ghosts",
	"Reforged Gunbelt of the Knight",
	"Hollow Girdle of the Steward",
	"Girdle of Doomed Worlds",
	"Links of Silent Worlds",
	"Bronzed Band of Infinite Protection",
	"Adamantite Girdle of Eternal Honor",
	"Peacekeeper's Bronzed Cord",
	"Battleworn Iron Band",
	"Bandit's Mithril Band",
	"Yearning Waistband of Regret",
	"Banished Links of the Crown",
	"Defender Waistband of Fire Protection",
	"Cord of Broken Illusions",
	"Band of Infernal Sorrow",
	"Golden Gunbelt of Hellish Punishment",
	"Skeletal Cord of Timeless Nightmares",
	"Stormguard Demon Waistguard",
	"Iron Cord",
	"Promised Titanium Girdle",
	"Thundersoul Belt of the Void",
	"Timeworn Links of Resilience",
	"Thundersoul Belt of Discipline",
	"Links of Infernal Comrades",
	"Cord of Endless Visions",
	"Demon Band of Ending Ancestors",
	"Ivory Links of Ending Justice",
	"Reincarnated Silver Girdle",
	"Ruby Infused Titanium Girdle",
	"Ominous Scaled Links",
	"Mourning Belt of Silence",
	"Spite Belt of Strength",
	"Thunder Waistband of the Forsaken",
	"Band of Immortal Freedom",
	"Gunbelt of Distant Visions",
	"Bone Gunbelt of Shattered Fortune",
	"Titanium Chain of Ending Wars",
	"Peacekeeper's Mithril Chain",
	"Ancient Silver Girdle",
	"Guardian's Obsidian Gunbelt",
	"Ruby Infused Girdle of the Forgotten",
	"Primitive Band of the Gladiator",
	"Defiled Girdle of the Breaking Storm",
	"Girdle of Fallen Powers",
	"Band of Damned Hell",
	"Steel Cord of Divine Lands",
	"Golden Cord of Eternal Glory",
	"Lich Obsidian Gunbelt",
	"Defiled Silver Girdle",
	"Heartless Ebon Waistguard",
	"Recruit's Links of the End",
	"Tormented Chain of the Prophecy",
	"Doom Waistband of Barriers",
	"Girdle of Relentless Bloodlust",
	"Waistband of Smoldering Fortunes",
	"Bone Girdle of Damned Powers",
	"Demon Belt of Eternal Dreams",
	"Singing Mithril Cord",
	"Lonely Steel Links",
	"Defiled Titanium Gunbelt",
	"Desire's Cord of Duels",
	"Exile Cord of the Lion",
	"Fiery Waistguard of the Sun",
	"Cord of Ending Visions",
	"Waistguard of Haunted Voices",
	"Ivory Chain of Twisted Dreams",
	"Bone Belt of Holy Punishment",
	"Captain's Ebon Waistband",
	"War-Forged Iron Gunbelt",
	"Golden Girdle",
	"Blood-Forged Links of Subtlety",
	"Champion Chain of the Depth",
	"Dragon Waistband of Justice"
};


static std::vector<std::string> bracerNames = {
	"Armguards of Cursed Trials",
	"Armbands of Blessed Warlords",
	"Ivory Vambraces of Lost Voices",
	"Ebon Wristguards of Infinite Protection",
	"Thunderfury Ivory Bracers",
	"Battleworn Bone Vambraces",
	"Captain's Silver Armguards",
	"Blood-Forged Armguards of Eternal Damnation",
	"Barbarian Wristguards of the Stars",
	"Soldier's Armbands of Slaying",
	"Armguards of Shattered Voices",
	"Bracers of Sacred Fortune",
	"Demon Wristguards of Immortal Sorrow",
	"Chainmail Bracers of Divine Power",
	"Champion's Scaled Bracers",
	"Relentless Obsidian Vambraces",
	"Bloodied Skeletal Wristguards",
	"Malicious Wristguards of the Lost",
	"Fortune's Vambraces of Anguish",
	"Honed Armbands of Ice Magic",
	"Armbands of Faded Trials",
	"Vambraces of Ominous Illusions",
	"Scaled Wristguards of Condemned Comrades",
	"Chainmail Bracers of Damned Ancestors",
	"Mail Bracers",
	"Mourning Scaled Vambraces",
	"Soldier's Mithril Armbands",
	"Terror Bracers of Limbo",
	"Fierce Armguards of Ruins",
	"Eternal Bracers of Storms",
	"Wristguards of Shattered Nightmares",
	"Vambraces of Damned Fortune",
	"Ebon Vambraces of Faded Vengeance",
	"Silver Armbands of Twisted Justice",
	"Stormguard Titanium Armbands",
	"Relentless Silver Bracers",
	"Gladiator's Chainmail Bracers",
	"Ghostly Vambraces of Vengeance",
	"Captain's Wristguards of Bravery",
	"Wristguards of Adventure",
	"Wristguards of Twisted Honor",
	"Bracers of Smoldering Nights",
	"Ebon Wristguards of Distant Nights",
	"Skeletal Bracers of Hellish Power",
	"Hollow Ebon Armbands",
	"Inherited Demon Bracers",
	"Whistling Golden Bracers",
	"Cataclysmic Vambraces of Nightmares",
	"Spite Armbands of the Sunwalker",
	"Vindicator Armguards of the Night",
	"Armbands of Lost Power",
	"Vambraces of Immortal Glory",
	"Mail Armguards of Eternal Souls",
	"Mithril Bracers of Dark Nights",
	"Warden's Titanium Armguards",
	"Extinction Bone Bracers",
	"Bloodied Titanium Vambraces",
	"Peacekeeper's Armguards of Ended Dreams",
	"Grieving Bracers of Prophecies",
	"Defender's Wristguards of Ghosts",
	"Armguards of Ancient Power",
	"Armbands of Condemned Protection",
	"Golden Wristguards of Twisted Sorrow",
	"Mail Bracers of Timeless Voices",
	"Adamantite Wristguards",
	"Soul Obsidian Armguards",
	"Fusion Skeletal Armguards",
	"Bloodsurge Vambraces of Doom",
	"Champion Wristguards of Deflection",
	"Barbarian Armbands of Black Magic",
	"Bracers of Distant Torment",
	"Bracers of Fleeting Torment",
	"Adamantite Bracers of Blessed Trials",
	"Skeletal Wristguards of Dark Sorrow",
	"Forsaken Bone Armguards",
	"War-Forged Bronze Wristguards",
	"Treachery's Bone Vambraces",
	"Keeper's Bracers of Demon Fire",
	"Knightly Armguards of Paradise",
	"Unholy Armbands of the Storm",
	"Armbands of Divine Power",
	"Vambraces of Lost Memories",
	"Chain Bracers of Ending Trials",
	"Demon Armguards of Hallowed Glory",
	"Peacekeeper Skeletal Bracers",
	"Bloodsurge Chain Armguards",
	"Cataclysmic Chainmail Bracers",
	"Sorrow's Wristguards of the Princess",
	"Mercenary Bracers of the Light",
	"Burnished Bracers of Darkness",
	"Armguards of Haunted Trials",
	"Armguards of Cursed Wars",
	"Bronzed Armbands of Infinite Nightmares",
	"Mithril Armbands of Shattered Misery",
	"Lightning Mithril Bracers",
	"Prime Chainmail Bracers",
	"Zealous Golden Vambraces",
	"Massive Wristguards of Fools",
	"Vindication Bracers of Storms",
	"Champion's Armguards of Terrors"
};


static std::vector<std::string> armorNames = {
	"Chestguard of Damned Freedom",
	"Batteplate of Infernal Hope",
	"Ebon Armor of Eternal Fortunes",
	"Silver Chestplate of Imminent Visions",
	"Hollow Iron Batteplate",
	"Timeworn Scaled Tunic",
	"Bloodied Chestplate of Bloodlust",
	"Primal Chestguard of Broken Dreams",
	"Emissary of the Occult",
	"Burden of Shadows",
	"Chestpiece of Distant Whispers",
	"Cuirass of Divine Whispers",
	"Bronze Chestguard of Endless Fire",
	"Bronze Chestpiece of Conquered Hope",
	"Ebon Steel Batteplate",
	"Ebon Bronzed Breastplate",
	"Ghostly Breastplate of the Gargoyle",
	"Ghost-Forged Chestplate of Oblivion",
	"Dawn of Pride",
	"Breastplate of Forging",
	"Cuirass of Divine Might",
	"Tunic of Ancient Nights",
	"Demon Breastplate of Binding Bloodlust",
	"Skeletal Breastplate of Doomed Hell",
	"Dire Chainmail Greatplate",
	"Shadow Bronzed Batteplate",
	"Infused Chestplate of Ashes",
	"Cuirass of the Incoming Storm",
	"Bastion of Frost",
	"Fall of the Incoming Storm",
	"Chestpiece of Divine Glory",
	"Chestguard of Infernal Fire",
	"Ivory Greatplate of Blind Dreams",
	"Ivory Greatplate of Broken Trials",
	"Hero Ebon Tunic",
	"Restored Skeletal Chestpiece",
	"Lich Cuirass of Fallen Kings",
	"Bloodied Armor of Life",
	"Tribute of Mystery",
	"Vindicator of Life",
	"Greatplate of Infinite Trials",
	"Chestguard of Eternal Hells",
	"Iron Batteplate of Ancient Nights",
	"Chain Tunic of Smoldering Hell",
	"Firesoul Adamantite Greatplate",
	"Wretched Scaled Chestpiece",
	"Liar's Cuirass of the Sky",
	"Lich Vest of Oblivion",
	"Memory of Eternal Sorrow",
	"Foe of the Corrupted",
	"Vest of Conquered Misery",
	"Batteplate of Smoldering Nights",
	"Skeletal Chestpiece of Hellish Trials",
	"Steel Cuirass of Blessed Fortunes",
	"Warlord's Adamantite Chestpiece",
	"Challenger Silver Armor",
	"Renovated Greatplate of the Lone Wolf",
	"Ominous Armor of Souls",
	"Tunic of Hellfire",
	"Cry of War",
	"Armor of Immortal Ancestors",
	"Vest of Infernal Worlds",
	"Golden Cuirass of Condemned Justice",
	"Skeletal Tunic of Burning Illusions",
	"Twilight Ivory Breastplate",
	"Wretched Obsidian Armor",
	"Sinister Batteplate of the Forgotten",
	"Promised Batteplate of Resilience",
	"Curator of Immortality",
	"Birth of the Archer",
	"Tunic of Faded Fortune",
	"Chestplate of Haunted Visions",
	"Titanium Breastplate of Ending Freedom",
	"Mail Vest of Eternal Hope",
	"Defiled Mithril Cuirass",
	"Treachery's Steel Vest",
	"Remorse Vest of the West",
	"Soul Tunic of Bloodlust",
	"Promise of Oblivion",
	"Batteplate of the Enigma",
	"Chestpiece of Immortal Damnation",
	"Chestplate of Condemned Vengeance",
	"Scaled Tunic of Sacred Voices",
	"Mail Chestpiece of Cursed Honor",
	"Singing Bronzed Chestguard",
	"Grieving Bronzed Batteplate",
	"Storm-Forged Cuirass of Annihilation",
	"Soul-Forged Batteplate of Unholy Blight",
	"Blight of Blessed Fortunes",
	"Tribute of Assaults",
	"Chestguard of Infernal Power",
	"Chestpiece of Damned Glory",
	"Ivory Tunic of Distant Hell",
	"Scaled Greatplate of Broken Freedom",
	"Ritual Skeletal Breastplate",
	"Grieving Mail Armor",
	"Greatplate of Deception",
	"Soul Armor of Terror",
	"Cuirass of Denial",
	"Chestguard of Truths"
};


static std::vector<std::string> bootNames = {
	"Boots of Burning Voices",
	"Treads of Ominous Illusions",
	"Iron Walkers of Damned Sorrow",
	"Mithril Greaves of Ominous Comrades",
	"Ghostly Steel Feet",
	"Pride's Demon Warboots",
	"Vindication Mithril Warboots",
	"Dire Sabatons of Silence",
	"Terror Boots of Thieves",
	"Faithful Boots of Silence",
	"Stompers of Faded Memories",
	"Walkers of Ominous Whispers",
	"Steel Spurs of Ending Protection",
	"Silver Boots of Lost Comrades",
	"Timeworn Bone Greatboots",
	"Guard's Golden Treads",
	"Lightning Iron Sabatons",
	"Frozen Walkers of the Eclipse",
	"Mourning Boots of Stability",
	"Ruby Infused Treads of Devotion",
	"Footguards of Haunted Worlds",
	"Footguards of Damned Ancestors",
	"Mail Feet of Smoldering Honor",
	"Obsidian Spurs of Fleeting Nights",
	"Soul-Forged Scaled Footguards",
	"Ominous Bronzed Boots",
	"Fiery Adamantite Treads",
	"Vindicator Greaves of Nightmares",
	"Soldier's Warboots of the Forsaken",
	"Challenger Treads of the Void",
	"Treads of Relentless Vengeance",
	"Greaves of Burning Kings",
	"Mithril Feet of Conquered Torment",
	"Demon Stompers of Shattered Dreams",
	"Hopeless Scaled Greaves",
	"Bronze Treads",
	"Defender Skeletal Feet",
	"Possessed Greaves of Dominance",
	"Undead Sabatons of Phantoms",
	"Thundersoul Greaves of Arcane Power",
	"Feet of Burning Magic",
	"Stompers of Unholy Freedom",
	"Bronzed Treads of Burning Vengeance",
	"Ebon Boots of Dark Might",
	"Vengeful Silver Boots",
	"Proud Bronze Warboots",
	"Dragon's Steel Walkers",
	"Blood-Forged Treads of Giantslaying",
	"Ghost-Forged Footguards of Ruins",
	"Grieving Feet of the Whispers",
	"Warboots of Blind Visions",
	"Sabatons of Relentless Dreams",
	"Silver Stompers of Frozen Memories",
	"Titanium Spurs of Condemned Wars",
	"Dire Scaled Feet",
	"Forsaken Ivory Stompers",
	"Wind's Iron Warboots",
	"Firesoul Greaves of Blight",
	"Wrathful Treads of Mysteries",
	"Honor's Spurs of Broken Dreams",
	"Warboots of Blind Visions",
	"Sabatons of Relentless Dreams",
	"Silver Stompers of Frozen Memories",
	"Titanium Spurs of Condemned Wars",
	"Dire Scaled Feet",
	"Forsaken Ivory Stompers",
	"Wind's Iron Warboots",
	"Firesoul Greaves of Blight",
	"Wrathful Treads of Mysteries",
	"Honor's Spurs of Broken Dreams",
	"Feet of Faded Hells",
	"Stompers of Conquered Freedom",
	"Silver Feet of Twisted Power",
	"Chainmail Spurs of Blind Vengeance",
	"Timeworn Obsidian Walkers",
	"Frenzied Skeletal Greatboots",
	"Destiny's Silver Greatboots",
	"Burnished Stompers of the Dragons",
	"Forsaken Walkers of Visions",
	"Dragon's Sabatons of the Night",
	"Walkers of Blessed Dreams",
	"Greatboots of Ancient Fires",
	"Obsidian Sabatons of Distant Warlords",
	"Ivory Warboots of Shattered Hell",
	"Conqueror Golden Boots",
	"Woeful Mail Warboots",
	"Faith's Mail Sabatons",
	"Barbaric Greatboots of Wonders",
	"Haunted Stompers of the Immortals",
	"Rune-Forged Greatboots of Dread",
	"Boots of Endless Power",
	"Boots of Demonic Visions",
	"Scaled Spurs of Timeless Vengeance",
	"Bronzed Warboots of Burning Fortune",
	"Haunted Golden Spurs",
	"Extinction Ebon Feet",
	"Keeper's Skeletal Spurs",
	"Stormfury Sabatons of Grieving Widows",
	"Soldier's Boots of Cunning",
	"Knightly Greatboots of Ending Misery"
};